### ISSUE TITLE
Internal error while opening FSharp.Configuration

### ISSUE THREAD

**Issue by object** [fsprojects/FSharp.Configuration#55] opened 2015-03-16 07:03 UTC
If I try to open FSharp.Configuration namespace after loading FSharp.Configuration (and SharpYaml), then I get the following error:

error FS0192: internal error: CreateFile(0x80070003)

The same happens if I execute the statement type Settings = FSharp.Configuration.AppSettings<"app.config">

**Comment by vasily-kirichenko** [comment] 2015-03-22 06:53
Cannot reproduce it. I created a blank F# console app and add the NuGet package. Everything works:

![image](https://cloud.githubusercontent.com/assets/873919/6768389/1fa06456-d079-11e4-9ce5-572e89437897.png)

Could you run it under the debugger to see the stack trace?

**Comment by vasily-kirichenko** [comment] 2015-05-20 19:38
I'm closing it since cannot reproduce.

**Closed by vasily-kirichenko** 2015-05-20 19:38 UTC
