### ISSUE TITLE
AppConfig returns null

### ISSUE THREAD

**Issue by phleb3** [fsprojects/FSharp.Configuration#54] opened 2015-03-10 00:24 UTC
I used nuget to install fsharp.configuration, and followed the instructions. 
Code:

type Settings = AppSettings<"app.config">

then

let test1 = Settings.TestKey < this returns a null exception

**Comment by vasily-kirichenko** [comment] 2015-03-22 06:59
Could you show your `app.config`?

**Comment by Muhomorik** [comment] 2015-04-12 13:35
I am having the same problem on win, VS2013
An unhandled exception of type 'System.NullReferenceException' occurred in FSharp.Configuration.dll

	open FSharp.Configuration
	
	// Let the type provider do it's work
	type Settings = AppSettings<"App.config">
	
	[<EntryPoint>]
	let main argv = 
	    
	    printfn "%A" Settings.TestInt
	    0 // return an integer exit code

<?xml version="1.0" encoding="utf-8"?>
<configuration>

  
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
    <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
          <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
        </dependentAssembly>
      </assemblyBinding>
    </runtime>
  <appSettings>
    <add key="test2" value="Some Test Value 5"/>
    <add key="TestInt" value="102"/>
    <add key="TestBool" value="True"/>
    <add key="TestDouble" value="10.01"/>
    <add key="TestDateTime" value="2014-05-18 11:14:28Z"/>
    <add key="TestTimeSpan" value="00:12:30"/>
    <add key="TestUri" value="http://fsharp.org" />
  </appSettings>  
</configuration>

**Comment by Muhomorik** [comment] 2015-04-12 14:39
Funny thing.. tests are ok. Must be something with setup.

**Comment by MBrouns** [comment] 2015-04-13 10:01
Exactly the same problem here.

**Comment by vasily-kirichenko** [comment] 2015-05-20 19:35
I'm closing it since no repro have been supplied.

**Closed by vasily-kirichenko** 2015-05-20 19:35 UTC

**Comment by Muhomorik** [comment] 2015-05-20 22:41
This is a bug.
You have unhanded exception in AppSettingsTypeProvider (in my case) in 

> An unhandled exception of type 'System.NullReferenceException' occurred in FSharp.Configuration.dll

    let getConfigValue key 
        ...
        settings.[key].Value

Because var settings length is zero and you are trying to access key that doesn't exist. There should be either check if element exists or exception handling.

**Comment by Muhomorik** [comment] 2015-05-20 23:42
And it happens because sometimes (I can reproduce it with 100%) app.config content is not moved to ConsoleApplication1.exe.config file. It looks like it doesn't recognise small changes like formatting and depends on operation order (add code, add config / add config, add code).
So removing something big from file, recompiling it and then redo change (ctrl+z) solves the problem for me.
